/** Rótulos das ações registradas no log de atividades.
 * Módulo 100% client-safe (sem imports de servidor/prisma).
 */
export const activityLabel: Record<string, string> = {
  "organization.created": "criou a organização",
  "organization.updated": "atualizou a organização",
  "onboarding.completed": "concluiu o onboarding",
  "department.created": "criou o departamento",
  "department.updated": "atualizou o departamento",
  "department.deleted": "removeu o departamento",
  "team.created": "criou a equipe",
  "team.updated": "atualizou a equipe",
  "team.deleted": "removeu a equipe",
  "member.created": "adicionou o colaborador",
  "member.updated": "atualizou o colaborador",
  "member.deleted": "removeu o colaborador",
  "project.created": "criou o projeto",
  "project.updated": "atualizou o projeto",
  "project.deleted": "removeu o projeto",
  "task.created": "criou a tarefa",
  "task.updated": "atualizou a tarefa",
  "task.status": "mudou o status da tarefa",
  "task.deleted": "removeu a tarefa",
  "goal.created": "criou a meta",
  "goal.updated": "atualizou a meta",
  "goal.deleted": "removeu a meta",
  "event.created": "criou o evento",
  "event.deleted": "removeu o evento",
  "announcement.created": "publicou o aviso",
  "announcement.deleted": "removeu o aviso",
};